import Head from 'next/head'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import axios from 'axios'
import Result from '../components/Result'
import requests from '../utils/requests'

export default function Home({resultData}) {
  console.log(resultData.results)
  return (
    <div >
      <Head>
        <title>Hulu 3.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}

      <Header />

      {/* navbar */}
      <Navbar />
      {/* Result */}
      <Result results={resultData.results}/>
    </div>
  )
}
export const getServerSideProps=async(context)=>{
const genre=context.query.genre
const request=await axios.get(`https://api.themoviedb.org/3${requests[genre]?.url||requests.fetchThrillerMovies.url}`)
// request.json()
return{
  props:{
    resultData:request.data
  }
}
}
